################################### Cluster ###################################

cluster.name: estest

#################################### Node #####################################

node.name: "data6"
node.master: false
node.data: true

#################################### Index ####################################

index.number_of_shards: 6
index.number_of_replicas: 1

#################################### Paths ####################################

path.conf: /usr/share/elasticsearch/config
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs
path.plugins: /usr/share/elasticsearch/plugins

#################################### Plugin ###################################

# plugin.mandatory: mapper-attachments,lang-groovy

################################### Memory ####################################

bootstrap.mlockall: true

# Make sure that the ES_MIN_MEM and ES_MAX_MEM environment variables are set
# to the same value, and that the machine has enough memory to allocate
# for ElasticSearch, leaving enough memory for the operating system itself.
#
# You should also make sure that the ElasticSearch process is allowed to lock
# the memory, eg. by using `ulimit -l unlimited`.

############################## Network And HTTP ###############################

#network.bind_host: 0.0.0.0
#network.publish_host: 0.0.0.0
network.host: 0.0.0.0

transport.tcp.port: 9300
transport.tcp.compress: true

http.port: 9200

# DISABLE CORS IN PRODUCTION ENVIRONMENT!
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers: X-Requested-With, Content-Type, Content-Length

# http.max_content_length: 100mb
# http.enabled: false


################################### Gateway ###################################

gateway.recover_after_master_nodes: 1
gateway.recover_after_data_nodes: 6
gateway.recover_after_time: 5m
gateway.expected_master_nodes: 2
gateway.expected_data_nodes: 6

action.auto_create_index: false

action.disable_close_all_indices: true
action.disable_delete_all_indices: true
action.disable_shutdown: true

############################# Recovery Throttling #############################

cluster.routing.allocation.node_initial_primaries_recoveries: 4
cluster.routing.allocation.node_concurrent_recoveries: 2

indices.recovery.max_bytes_per_sec: 100mb
indices.recovery.concurrent_streams: 5

################################## Discovery ##################################

discovery.zen.minimum_master_nodes: 2
discovery.zen.ping.timeout: 3s

discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: ["master1", "master2"]

################################## Slow Log ##################################

#index.search.slowlog.threshold.query.warn: 10s
#index.search.slowlog.threshold.query.info: 5s
#index.search.slowlog.threshold.query.debug: 2s
#index.search.slowlog.threshold.query.trace: 500ms

#index.search.slowlog.threshold.fetch.warn: 1s
#index.search.slowlog.threshold.fetch.info: 800ms
#index.search.slowlog.threshold.fetch.debug: 500ms
#index.search.slowlog.threshold.fetch.trace: 200ms

#index.indexing.slowlog.threshold.index.warn: 10s
#index.indexing.slowlog.threshold.index.info: 5s
#index.indexing.slowlog.threshold.index.debug: 2s
#index.indexing.slowlog.threshold.index.trace: 500ms

################################## GC Logging ################################

#monitor.jvm.gc.ParNew.warn: 1000ms
#monitor.jvm.gc.ParNew.info: 700ms
#monitor.jvm.gc.ParNew.debug: 400ms

#monitor.jvm.gc.ConcurrentMarkSweep.warn: 10s
#monitor.jvm.gc.ConcurrentMarkSweep.info: 5s
#monitor.jvm.gc.ConcurrentMarkSweep.debug: 2s
